Familia = input('Введите фамилию')
Name = input('Введите Имя')
Group = input('Введите Групу')
City = input('Введите Город')
Age = int(input('Введите возраст'))
lub_pr =  input('Любимый предмет')
hour_in_weak = input('сколько часов в неделю вы учитесь')
print(Familia)
print(Name)
print(Group)
print(City)
print(Age)
print(lub_pr)
print(hour_in_weak)
